version: "3"

services:
  backend:
    env_file:
        "./server/.env"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "pwitter-backend"
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "pwitter-frontend"
    ports:
      - "3000:3000"
    links:
      - "backend"